Documentation:
- changed-files:
  - any-glob-to-any-file:
    - docs/*
    - README.md

"GitHub Actions Workflow":
- changed-files:
  - any-glob-to-any-file:
    - .github/workflows/*

"Bitrise Workflow":
- changed-files:
  - any-glob-to-any-file:
    - bitrise.yml

"CircleCI Workflow":
- changed-files:
  - any-glob-to-any-file:
    - .circleci/config.yml

iOS:
- changed-files:
  - any-glob-to-any-file:
    - ci-sample/*
    - ci-sample.xcodeproj/*

Fastlane:
- changed-files:
  - any-glob-to-any-file:
    - fastlane/*
