language: swift

osx_image: xcode8.3

xcode_project: ci-sample.xcodeproj
xcode_scheme: ci-sample

before_install:
  - openssl aes-256-cbc -K $encrypted_447977b53217_key -iv $encrypted_447977b53217_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d
  - tar xvf ./travis/secrets.tar -C ./travis
  - gem install xcpretty-travis-formatter --no-document
  - bundle install --path ./vendor/bundle

before_script:
  - security create-keychain -p travis ios-build.keychain
  - security default-keychain -s ios-build.keychain
  - security unlock-keychain -p travis ios-build.keychain
  - security import ./travis/apple.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
  - security import ./travis/dist.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
  - security import ./travis/dist.p12 -k ~/Library/Keychains/ios-build.keychain -P $KEY_PASSWORD -T /usr/bin/codesign
  - security set-key-partition-list -S apple-tool:,apple: -s -k travis ios-build.keychain
  - mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
  - cp ./travis/*mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

script:
  - security unlock-keychain -p sample ios-build.keychain
  - bundle exec fastlane build

after_success:

after_script:
  - security delete-keychain ios-build.keychain
  - rm -f "~/Library/MobileDevice/Provisioning Profiles/"

notifications:
  email: false