language: swift

osx_image: xcode8.3

xcode_project: ci-sample.xcodeproj
xcode_scheme: ci-sample

before_install:
  - openssl aes-256-cbc -K $encrypted_448470aeb6e7_key -iv $encrypted_448470aeb6e7_iv -in ./travis/secrets.tar.enc -out ./travis/secrets.tar -d
  - tar xvf ./travis/secrets.tar -C ./travis
  - gem install xcpretty-travis-formatter --no-document
  - bundle install --path ./vendor/bundle

before_script:
  - bundle exec fastlane setup_certificate
  - mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
  - cp ./travis/*mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

script:
  - bundle exec fastlane build

after_success:

after_script:
  - security delete-keychain ios-build.keychain
  - rm -f "~/Library/MobileDevice/Provisioning Profiles/"

notifications:
  email: false
