version: 2.1

jobs:
  build:
    macos:
      xcode: 15.2.0 

    steps:
      - checkout
      - run: fastlane test
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output

workflows:
  build:
    jobs:
      - build