# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:
    macos:
      xcode: "10.2.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
      - run: bundle install
      - run:
          name: build
          command: bundle exec fastlane build

  test:
    macos:
      xcode: "10.2.0"
    working_directory: /Users/distiller/project

    steps:
      - checkout
      - run: bundle install
      - run:
          name: run test
          command: bundle exec fastlane test

      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

  deploygate:
    macos:
      xcode: "10.2.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
      - run: bundle install
      - run:
          name: upload to deploygate
          command: bundle exec fastlane upload_deploygate


  update_metadata:
    macos:
      xcode: "10.2.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
      - run: bundle install
      - run:
          name: update metadata
          command: bundle exec fastlane update_metadata


  release:
    macos:
      xcode: "10.2.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
      - run: bundle install
      - run:
          name: release
          command: bundle exec fastlane release


workflows:
  version: 2
  feature:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploygate:
          requires:
            - build
          filters:
            branches:
              only: /support\/.*/
  release:
    jobs:
      - test:
          filters:
            branches:
              only: /release*/
      - release_build:
          requires:
            - test
      - update_metadata:
          requires:
            - release_build
