version: 2.1

jobs:
  test:
    macos:
      xcode: 15.2.0
    steps:
      - checkout
      - run: fastlane test
      - store_test_results:
          path: test_result
      - store_artifacts:
          path: test_result
          destination: scan-output
  build:
    macos:
      xcode: 15.2.0 
    steps:
      - checkout
      - run: fastlane build_for_simulator
      - store_artifacts:
          path: build_result
          destination: build-output

workflows:
  build_and_test:
    jobs:
      - build
      - test