# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  sample:
    macos:
      xcode: "10.2.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
      - run: bundle install

  build:
    macos:
      xcode: "10.2.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
      - run: bundle install
      - run:
          name: build
          command: bundle exec fastlane build

  test:
    macos:
      xcode: "10.2.0"
    working_directory: /Users/distiller/project

    steps:
      - checkout
      - run: bundle install
      - run:
          name: run test
          command: bundle exec fastlane test

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
      - sample
          branches:
          only: /support\/.*/

