version: 2.1

jobs:
  test:
    macos:
      xcode: 15.2.0
    steps:
      - checkout
      - run: fastlane test
      - store_test_results:
          path: test_result
      - store_artifacts:
          path: test_result
          destination: scan-output
  build:
    macos:
      xcode: 15.2.0 
    steps:
      - checkout
      - run:
          name: Archive
          command: |
            xcodebuild archive CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -project ./ci-sample.xcodeproj -scheme ci-sample -configuration Debug -archivePath ./ci-sample_debug
      - run:
          name: ipa
          command: |
            echo "${AUTHKEY_P8_BASE64}" | base64 -d > $PWD/Authkey.p8
            xcodebuild -exportArchive -archivePath ci-sample_debug.xcarchive -exportPath ./build_result -exportOptionsPlist ./ExportOptions.plist -allowProvisioningUpdates -authenticationKeyIssuerID ${ISSUER_ID} -authenticationKeyID ${KEY_ID} -authenticationKeyPath $PWD/Authkey.p8
      - store_artifacts:
          path: build_result
          destination: build-output

workflows:
  build_and_test:
    jobs:
      - build
      - test
  cron_workflow:
    triggers:
      - schedule:
          cron: "0 15 10 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
