skip_docs

default_platform :ios

platform :ios do
  desc "run test"
  lane :test do
    run_tests(
      output_directory: "./test_result"
    )
  end


  lane :upload_ipa_for_testflight do
    key_id = ENV["KEY_ID"]
    issuer_id = ENV["ISSUER_ID"]
    ipa_file_path = ENV["IPA_FILE_PATH"]
    auth_key_p8_path = ENV["AUTHKEY_P8_FILE_PATH"]

    app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_filepath: auth_key_p8_path,
      duration: 1200,
      in_house: false
    )

    upload_to_testflight(
      ipa: ipa_file_path,
      skip_submission: true,
    )
  end

  desc "build Simulator File"
  lane :build_for_simulator do
    build_app(
      project: "./ci-sample.xcodeproj",
      scheme: "ci-sample",
      derived_data_path: "./build",
      skip_archive: true,
      destination: "generic/platform=iOS Simulator",
      output_directory: "./build_result",
    )
  end


end
