default_platform :ios

platform :ios do
  keychain_name = "ios-build.keychain"
  keychain_password = SecureRandom.base64
  build_number = ENV["BUILD_NUMBER"] ||= "0"

  lane :test do
    scan
  end

  desc "build Simulator File"
  lane :build_for_simulator do
    build_app(
      project: "./ci-sample.xcodeproj",
      scheme: "ci-sample",
      derived_data_path: "./build",
      skip_archive: true,
      destination: "generic/platform=iOS Simulator"
    )
  end


  lane :build_debug_without_match do
    clean_build_artifacts
    increment_build_number(
      build_number: "0." + ENV["BUILD_NUMBER"]
    )

    build(type: "Debug")
  end

  lane :build_debug do
    match(type: "development", readonly: is_ci)

    clean_build_artifacts
    increment_build_number(
      build_number: "0." + ENV["BUILD_NUMBER"]
    )

    build(type: "Debug")
  end

  lane :build_release do
    match(type: "appstore", readonly: is_ci)

    clean_build_artifacts
    increment_build_number(
      build_number: "1." + ENV["BUILD_NUMBER"]
    )

    build(type: "Release")
  end


  lane :testflight do
      upload_to_testflight(
      username: "felix@krausefx.com",
      app_identifier: "com.krausefx.app",
      itc_provider: "abcde12345" # pass a specific value to the iTMSTransporter -itc_provider option
    )
  end

  private_lane :build do |options|
    configuration = options[:type]
    export_method = configuration == "Release" ? "appstore" : "development"

    gym(
      project: "./ci-sample.xcodeproj",
      scheme: "ci-sample",
      configuration: configuration,
      export_method: export_method
    )
  end
end
