name: Cron

on:
  schedule:
    - cron: '0 15 10 * *'

permissions: write-all

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 40
    env:
      DEVELOPER_DIR: "/Applications/Xcode_15.4.app/Contents/Developer"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: archive
        run: |
          xcodebuild archive CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -project ./ci-sample.xcodeproj -scheme ci-sample -configuration Debug -archivePath ./ci-sample_debug
      - name: upload testflight
        env:
          AUTHKEY_P8_BASE64: ${{ secrets.AUTHKEY_P8_BASE64 }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          KEY_ID: ${{ secrets.KEY_ID }}
        run: |
          echo $AUTHKEY_P8_BASE64 | base64 -d > $PWD/Authkey.p8
          xcodebuild -exportArchive -archivePath ci-sample_debug.xcarchive -exportPath ./build_result -exportOptionsPlist ./ExportOptionsTestFlight.plist -allowProvisioningUpdates -authenticationKeyIssuerID $ISSUER_ID -authenticationKeyID $KEY_ID -authenticationKeyPath $PWD/Authkey.p8
