name: "Pull Request Labeler"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
      with:
        sync-labels: true
        dot: true
