name: PullRequest

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
      - name: archive
        run: |
          xcodebuild archive CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -project ./ci-sample.xcodeproj -scheme ci-sample -configuration Debug -archivePath ./ci-sample_debug
      - name: ipa
        env:
          AUTHKEY_P8_BASE64: ${{ secrets.AUTHKEY_P8_BASE64 }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          KEY_ID: ${{ secrets.KEY_ID }}
        run: |
          echo $AUTHKEY_P8_BASE64 | base64 -d > $PWD/Authkey.p8
          xcodebuild -exportArchive -archivePath ci-sample_debug.xcarchive -exportPath ./build_result -exportOptionsPlist ./ExportOptions.plist -allowProvisioningUpdates -authenticationKeyIssuerID $ISSUER_ID -authenticationKeyID $KEY_ID -authenticationKeyPath $PWD/Authkey.p8
      - name: Cache bundle directory
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Setup
        shell: bash
        id: setup
        run: |
          bundle config set path 'vendor/bundle'
          bundle install
      - name: test flight
        env:
          AUTHKEY_P8_BASE64: ${{ secrets.AUTHKEY_P8_BASE64 }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          KEY_ID: ${{ secrets.KEY_ID }}
          IPA_FILE_PATH: "./build_result/ci-sample.ipa"
          AUTHKEY_P8_FILE_PATH: "./Authkey.p8"
        run: |
          bundle exec fastlane upload_ipa_for_testflight


  test:
    runs-on: macos-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
      - name: Cache bundle directory
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: bundler
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: test
        run: |
          bundle exec fastlane test
