name: iOS Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: archive
        run: |
          xcodebuild archive CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -project ./ci-sample.xcodeproj -scheme ci-sample -configuration Debug -archivePath ./ci-sample_debug
      - name: ipa
        env:
          AUTHKEY_P8_BASE64: ${{ secrets.AUTHKEY_P8_BASE64 }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          KEY_ID: ${{ secrets.KEY_ID }}
        run: |
          echo "${AUTHKEY_P8_BASE64}" | base64 -d > "${PWD}/Authkey.p8"
          xcodebuild -exportArchive -archivePath ci-sample_debug.xcarchive -exportPath ./build_result -exportOptionsPlist ./ExportOptions.plist -allowProvisioningUpdates -authenticationKeyIssuerID "${ISSUER_ID}" -authenticationKeyID "${KEY_ID}" -authenticationKeyPath "${PWD}/Authkey.p8"
          zip -r ci-sample.zip ./build_result/ci-sample.ipa
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          tag_name: ${{ github.ref_name }}
          name: "CI Sample Release ${{ github.ref_name }}"
          generate_release_notes: true
          prerelease: false
          fail_on_unmatched_files: true
          files: ci-sample.zip
